name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: nod-ai-shared-cpubuilder-manylinux-x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

# see https://black.readthedocs.io/en/stable/integrations/github_actions.html
